const MessageType = {
    TEAM_FORMATION: 'TEAM_FORMATION',
    MASTER_CHECK: 'MASTER_CHECK',
    ASK_MASTER: 'ASK_MASTER',
    ASK_FOR_PLAN: 'ASK_FOR_PLAN',
    PLAN_ASSIGNMENT: 'PLAN_ASSIGNMENT',
    UPDATE_BELIEFS: 'UPDATE_BELIEFS',
    UPDATE_PARCELS_BELIEFS: 'UPDATE_PARCELS_BELIEFS',
    UPDATE_PLAYERS_BELIEFS: 'UPDATE_PLAYERS_BELIEFS',
    UPDATE_OPTION: 'UPDATE_OPTION',
    DELETE_OPTION: 'DELETE_OPTION',
    POSITION_UPDATE: 'POSITION_UPDATE'
};

export default MessageType;
